import { readFileSync } from 'node:fs'
import { join, relative, sep } from 'node:path'

import { globSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

/**
 * The service role bypasses every policy in `supabase/`. It is the one
 * credential that makes the whole of this repo's security work irrelevant, so
 * the question is not whether it is used correctly today but whether it stays
 * out of the places where it would be a shortcut tomorrow.
 *
 * It is a shortcut whenever RLS is inconvenient: a query returns nothing, the
 * quickest way to make it return something is the service key, and the fix
 * looks like it works. This test is what stops that being quiet.
 *
 * Two trees are off limits entirely:
 *
 *   src/                  runs in a browser. A service key here would ship in
 *                         the bundle, which the CI build-output grep also
 *                         catches — but by then it has been written, reviewed
 *                         and merged.
 *   supabase/functions/   runs on the server, where the key is available and
 *                         where reaching for it is genuinely tempting. The
 *                         check-in function deliberately does not: the
 *                         escalation lives in a SECURITY DEFINER function that
 *                         does exactly one thing, and the database enforces
 *                         the contract instead of the TypeScript.
 *
 * `tests/rls/` is allowed to use it, against the local stack only, because
 * proving that a member's count is filtered requires knowing the unfiltered
 * one. That key is generated by `supabase start` and read at runtime; it is
 * never written down.
 */

const FORBIDDEN = /service_role|SERVICE_ROLE|sb_secret_/

const TREES = ['src', join('supabase', 'functions')]

function sourceFiles(tree: string): string[] {
  try {
    return globSync(join(tree, '**', '*.{ts,tsx,js,jsx}'))
  } catch {
    return []
  }
}

describe('the service role stays out of shipped code', () => {
  it.each(TREES)('%s mentions no privileged credential', (tree) => {
    const offenders = sourceFiles(tree)
      .filter((file) => FORBIDDEN.test(readFileSync(file, 'utf8')))
      .map((file) => relative(process.cwd(), file).split(sep).join('/'))

    expect(
      offenders,
      `The service role bypasses every policy. If a query is coming back empty, the ` +
        `answer is a policy or a SECURITY DEFINER function, not this key.\n  ` +
        offenders.join('\n  '),
    ).toEqual([])
  })

  it('and does not appear in .env.example, not even as an empty name', () => {
    // A commented-out name is an invitation: it tells the next person the
    // variable is expected and gives them somewhere to paste a real value.
    expect(FORBIDDEN.test(readFileSync('.env.example', 'utf8'))).toBe(false)
  })
})
