-- An idea written down without a connection.
--
-- The screen promises it: "se't desa i puja quan torni la connexió". Keeping
-- that promise needs one thing from the database — a way for a resend to be
-- the same idea rather than a second one.
--
-- The door solved this with `points_log.client_request_id`, a client-generated
-- key with a unique index behind it. A proposal already has a uuid primary
-- key; it just was not the client's to set. Now it is, and a flush that runs
-- twice collides on the key instead of posting the idea again.
--
-- Letting a client choose a primary key is safe here and not elsewhere: it is
-- a uuid, so it leaks nothing and collides with nothing, and `prop_insert_self`
-- still decides whose row it is.
grant insert (id) on public.proposals to authenticated;

comment on column public.proposals.id is
  'Generated by the client so that resending a queued idea is idempotent. The '
  'insert grant includes it for that reason and no other — see the offline '
  'queue in src/lib/queue.ts.';
